(define (problem put-wuti)
   (:domain pick-and-place)
   (:objects
          v0 - config
          v7 v9 v5 v3 v4 v1 v6 - wuti
          v8 v2 v10 - pose
   )
   (:init
          (atconf v0)
          (atpose v1 v2)
          (atpose v7 v8)
          (atpose v9 v10)
          (canmove)
          (fixed v3)
          (fixed v4)
          (fixed v5)
          (fixed v6)
          (followold)
          (graspable v1)
          (graspable v7)
          (graspable v9)
          (handempty)
          (isconf v0)
          (ispose v1 v2)
          (ispose v7 v8)
          (ispose v9 v10)
          (issink v4)
          (isstove v5)
          (issupport v1 v2 v3)
          (issupport v7 v8 v3)
          (issupport v9 v10 v3)
          (stackable v1 v3)
          (stackable v1 v4)
          (stackable v1 v5)
          (stackable v1 v6)
          (stackable v7 v1)
          (stackable v7 v3)
          (stackable v7 v4)
          (stackable v7 v5)
          (stackable v7 v6)
          (stackable v9 v1)
          (stackable v9 v3)
          (stackable v9 v4)
          (stackable v9 v5)
          (stackable v9 v6)
          (stackable v9 v7)
   )
   (:goal
      (and
          (atconf v0)
          (on v1 v4)
          (on v7 v4)
          (on v9 v4)
      )
   )
)
